// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_template/test/notifications/notification_manager_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_template/notifications/data/message.dart' as _i1;
import 'package:flutter_template/notifications/data/message_handler.dart' as _i3;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [MessageHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageHandler<E extends _i1.Message> extends _i2.Mock
    implements _i3.MessageHandler<E> {
  MockMessageHandler() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> handleMessage(E? message) =>
      (super.noSuchMethod(Invocation.method(#handleMessage, [message]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
