// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_template/test/notifications/notification_multi_parser_test.dart.
// Do not manually edit this file.

import 'package:flutter_template/notifications/data/message.dart' as _i2;
import 'package:flutter_template/notifications/data/message_parser.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMessage_0 extends _i1.Fake implements _i2.Message {}

/// A class which mocks [MessageParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageParser extends _i1.Mock implements _i3.MessageParser {
  MockMessageParser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Message parseMessage(dynamic remoteData) =>
      (super.noSuchMethod(Invocation.method(#parseMessage, [remoteData]),
          returnValue: _FakeMessage_0()) as _i2.Message);
  @override
  String toString() => super.toString();
}
